# Generated by Django 5.2 on 2025-05-02 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('ownership_type', models.CharField(max_length=100, verbose_name='Вид собственности')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код ценной бумаги')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Мин. сумма сделки')),
                ('rating', models.PositiveIntegerField(verbose_name='Рейтинг')),
                ('last_year_yield', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доходность за прошлый год')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процентная ставка')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Котировка')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата котировки')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.security')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Дата продажи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deposit')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.security')),
            ],
        ),
    ]
