# Generated by Django 5.2 on 2025-05-02 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Сумма инвестиции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='security',
            name='currency',
            field=models.CharField(default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='security',
            name='issuer',
            field=models.CharField(default=2, max_length=200, verbose_name='Эмитент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='security',
            name='security_type',
            field=models.CharField(choices=[('stock', 'Акция'), ('bond', 'Облигация'), ('etf', 'ETF'), ('other', 'Другое')], default='stock', max_length=20, verbose_name='Тип ценной бумаги'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deposit', verbose_name='Депозит'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.security', verbose_name='Ценная бумага'),
        ),
    ]
