# Generated by Django 5.2 on 2025-05-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_investment_amount_security_currency_security_issuer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='security',
            name='name',
            field=models.CharField(default=2, max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='security',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='security',
            name='last_year_yield',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доходность (%)'),
        ),
        migrations.AlterField(
            model_name='security',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Мин. сумма'),
        ),
        migrations.AlterField(
            model_name='security',
            name='security_type',
            field=models.CharField(choices=[('stock', 'Акция'), ('bond', 'Облигация'), ('etf', 'ETF'), ('other', 'Другое')], max_length=20, verbose_name='Тип'),
        ),
    ]
