# Generated by Django 5.2 on 2025-05-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_investment_amount_alter_investment_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма инвестиции'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deposit', verbose_name='Депозит'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='purchase_date',
            field=models.DateField(verbose_name='Дата покупки'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.security', verbose_name='Ценная бумага'),
        ),
    ]
