# Generated by Django 5.2 on 2025-05-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_investment_amount_alter_investment_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ownership_type',
            field=models.CharField(choices=[('ООО', 'Общество с ограниченной ответственностью'), ('ИП', 'Индивидуальный предприниматель'), ('АО', 'Акционерное общество')], max_length=50, verbose_name='Тип собственности'),
        ),
    ]
