# Generated by Django 5.2 on 2025-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_ownership_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotehistory',
            options={'ordering': ['-date'], 'verbose_name': 'История котировок', 'verbose_name_plural': 'История котировок'},
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='quotehistory',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='quotehistory',
            name='quote',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
